% Design and analysis script for ME 4550 final design project
%
% Matthew Bonanni, Nicolas Iacovelli, Adrian Kombe, Ryan Loehr, Becca Sung

%% Parameters and Characteristics

% Gear diameters

d_A = 24;
d_C = 10;

% Load parameters

P_Angle = 20;
P_A = 600;

% Length parameters

OA = 20;
AB = 16;
BC = 10;

% Strength characteristics

n = 3;
Sy = 71000;
Sut = 85000;

%% Force balance

% Breaking P_A into components

A_y = P_A * cosd(P_Angle);
A_z = -P_A * sind(P_Angle);

% The torque generated by P_A

T = A_y * (d_A/2);

% Calculate P_C from torque balance

C_z = -T / (d_C / 2);
P_C = -C_z / cosd(P_Angle);
C_y = P_C * sind(P_Angle);

% Z Moment balance around B

O_y = -(A_y * AB + C_y * BC) / (OA + AB);
B_y = -O_y - A_y + C_y;

% Y Moment balance around B

O_z = -(A_z * AB + C_z * BC) / (OA + AB);
B_z = O_z - A_z + C_z;

% Moments at A

M_Ay = O_z * OA;
M_Az = -O_y * OA;
M_A_tot = sqrt((M_Ay^2) + (M_Az)^2);

% Moments at B

M_By = -C_z * BC;
M_Bz = C_y * BC;
M_B_tot = sqrt((M_By^2)+(M_Bz^2));

%% Stresses

M_a = max(M_A_tot, M_B_tot);

% Critical point determined to be at B, where M_tot is largest

syms d % symbolic shaft diameter

sigma_a = (32* M_a / (pi*d^3));
sigma_m = 0;
M_m = 0;
tao_a = 0;
T_a = 0;
tao_m = (16* M_a / (pi*d^3));
T_m = T;

Kf = 1;
Kfs = 1;

sigma_a_prime = ((Kf*sigma_a)^2+3*(Kfs*tao_a)^2)^.5;
sigma_m_prime = ((Kf*sigma_m)^2+3*(Kfs*tao_m)^2)^.5;

% Fatigue failure conditions
Se_prime = Sut * .5;
ka_a = 2.7;
ka_b = -.265;
ka = (ka_a)*((Sut/1000)^(ka_b));
kb = .9;   %guess for fist iteration
kc = 1;     %1 for combined loading

Se = (ka * kb * kc * Se_prime);

%% Diameter calculation based on fatigue approach
% Using DE-Goodman Method

tolerance = 1;
MGM_dnext = 6; % Initial diameter assumption

while tolerance >= .001
    MGM_d = double(solve(((16 * n / (pi * d^3)) * ((Se^-1) * sqrt((4 * Kf * M_a)^2 + ...
        3 * (Kfs * T_a)^2) + (Sut^-1) * sqrt(4 * (Kf * M_m)^2 + 3 * (Kfs * T_m)^2))) - 1));
    
    MGM_d = MGM_d((MGM_d > 0) & imag(MGM_d) == 0); % Select real, positive solution
    tolerance = abs(((MGM_d - MGM_dnext) / MGM_d));
    MGM_dnext = MGM_d;
    kb = (.879 * MGM_d^-.107);
    Se = (ka * kb * kc * Se_prime);
end

% Using DE-Gerber Method

tolerance = 1;
Ger_dnext = 6; % Initial diameter assumption

while tolerance >= .001
    Ger_d = double(solve( (n*sigma_a_prime/Se) + (n*sigma_m_prime/Sy)^2 -1));
    
    Ger_d = Ger_d((Ger_d > 0) & imag(Ger_d) == 0); % Select real, positive solution
    tolerance = abs(((Ger_d - Ger_dnext) / Ger_d));
    Ger_dnext = Ger_d;
    kb = (.879 * Ger_d^-.107);
    Se = (ka * kb * kc * Se_prime);
end

% Using DE-ASME Elliptic Method

tolerance = 1;
ASME_dnext = 6; % Initial diameter assumption

while tolerance >= .001
    ASME_d = double(solve( (n*sigma_a_prime/Se)^2 + (n*sigma_m_prime/Sy)^2 -1));
    
    ASME_d = ASME_d((ASME_d > 0) & imag(ASME_d) == 0); % Select real, positive solution
    tolerance = abs(((ASME_d - ASME_dnext) / ASME_d));
    ASME_dnext = ASME_d;
    kb = (.879 * ASME_d^-.107);
    Se = (ka * kb * kc * Se_prime);
end

% Using DE-Soderberg Method

tolerance = 1;
Soder_dnext = 6; % Initial diameter assumption

while tolerance >= .001
    Soder_d = double(solve(((16 * n / (pi * d^3)) * ((Se^-1) * sqrt((4 * Kf * M_a)^2 + ...
        3 * (Kfs * T_a)^2) + (Sy^-1) * sqrt(4 * (Kf * M_m)^2 + 3 * (Kfs * T_m)^2))) - 1));
    
    Soder_d = Soder_d((Soder_d > 0) & imag(Soder_d) == 0); % Select real, positive solution
    tolerance = abs(((Soder_d - Soder_dnext) / Soder_d));
    Soder_dnext = Soder_d;
    kb = (.879 * Soder_d^-.107);
    Se = (ka * kb * kc * Se_prime);
end